config/routes.rb
Rails.application.routes.draw do
  get 'stocks/search'
  get 'users/my_portfolio'
  get 'welcome/index'
  
  post 'stocks/add'
  post 'stocks/remove_stock_from_portfolio'

  #devise_for :users
	
	devise_for :users, :controllers => { :registrations => "user/registrations" }
  
  root 'welcome#index'

  get 'my_friends', to: 'users#my_friends'
  get 'users/show_friend'
  get 'users/search_friend'
  post 'users/remove_friend'
  post 'users/add_friend'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/stock.rb
class Stock < ApplicationRecord
has_many :user_stocks
has_many :users, through: :user_stocks

def self.new_from_lookup(ticker_symbol)
	looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
	if looked_up_stock 
	  new(name: looked_up_stock.company_name, last_price: looked_up_stock.latest_price, ticker: looked_up_stock.symbol)

	end
end

def self.strip_commas(number)
  number.gsub(",", "")
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


	has_many :user_stocks
	has_many :stocks, through: :user_stocks
	has_many :friendships
	has_many :friends, through: :friendships

	def full_name
		if (first_name || last_name)
		  return "#{first_name} #{last_name}" 
		else
			"Anonymus"
		end 
	end

	def friend_with?(friend_id)
		friendships.where(friend_id: friend_id).count > 0
	end

	def self.search_friends(search_input)
		r = (search_by_field("email", search_input) + search_by_field("first_name", search_input) + search_by_field("last_name", search_input)).uniq
		if r 
			return r
		else
		  return nil
		end
	end

	def self.search_by_field(fieldname, search_input)
		r = where("#{fieldname} like?", "%#{search_input}%")
	end



end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
	
	def search
	  if params[:stock].present?
	    @stock = Stock.new_from_lookup(params[:stock])
	    if @stock
	      respond_to do |format|
	      	format.html
	        format.js { render partial: 'stocks/result' }
	      end
	    else
	    	respond_to do |format|
	    		format.html
	        
	        format.js { 
	        	flash.now[:danger] = "You have entered an incorrect symbol2"
	        	render partial: 'stocks/result' 
	        }
	  	  end
	  	end
	  else
	  	respond_to do |format|
	  		format.html
	    	
	    	format.js {
					flash.now[:danger] = "You have entered an empty search string2"
	    		render  partial: 'stocks/result' 
	    	}
	  	end
		end
	end

	def add
		if params[:stock].present?
	    @stock = Stock.new_from_lookup(params[:stock])
			duplicate = false
			current_user.stocks.each do |stock|
				if stock.ticker == @stock.ticker
					duplicate = true
				end
			end
			if duplicate
				flash[:danger] = "Stock already included in Portfolio"
				redirect_to users_my_portfolio_path(current_user)
			else
				@stock.users.append(current_user)
				if @stock.save 
					flash[:success] = "Stock added to Portfolio"
					redirect_to users_my_portfolio_path(current_user)
				else
					flash[:danger] = "Stock could not be added"
					redirect_to users_my_portfolio_path(current_user)
				end
			end
		end
	end

	def remove_stock_from_portfolio
		stock = Stock.where(ticker: params[:stock])
		
		us = UserStock.where(user: current_user)

		
		
		if us.delete(stock)
			flash[:success] = "Stock removed from Portfolio"
			redirect_to users_my_portfolio_path(current_user)
		else
			flash[:danger] = "Stock could not be removed"
			redirect_to users_my_portfolio_path(current_user)
		end
	end


end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user_stocks = current_user.stocks
    @user = current_user
  end

  def my_friends
  	@my_friends = current_user.friends
  end

  def remove_friend
		friend = User.where(id: params[:friend_id])
		user_friend = Friendship.where(user: current_user, friend: friend).first
		if user_friend.delete
			flash[:success] = "Friendship deleted"
			redirect_to my_friends_path
		else
			flash[:danger] = "Friendship could not be deleted."
			redirect_to my_friends_path
		end
	end


	def add_friend
		friend = User.find(params[:friend_id])
		if friend == current_user
			flash[:danger] = "You can not add yourself!"
			redirect_to my_friends_path
		elsif current_user.friend_with?(friend.id)
			flash[:danger] = "You are already friends!"
			redirect_to my_friends_path
		else
			new_friendship = Friendship.new(user: current_user, friend: friend)
			if new_friendship.save
				flash[:success] = "Friend added"
				redirect_to my_friends_path
			else
				flash[:danger] = "Friend could not be added."
				redirect_to my_friends_path
			end
		end
	end



	def show_friend
		@friend = User.find(params[:friend_id])
	end


	def search_friend
		if params[:search_input].present?
			@friends = User.search_friends(params[:search_input])
			if @friends.include?(current_user)
				@friends.delete(current_user)
			end

			if @friends && @friends.size > 0
				 respond_to do |format|
		      	format.html
		        format.js { render partial: 'users/result' }
		     end
		  else
		  	respond_to do |format|
		   		format.html
		      format.js { 
		       	flash.now[:danger] = "Nothing found!"
		       	render partial: 'users/result' 
		        }
		     end
		  end
		else
	  	respond_to do |format|
	  		format.html	
	    	format.js {
					flash.now[:danger] = "You have entered an empty search string"
	    		render  partial: 'users/result' 
	    	}
	  	end
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
	<li class='user-name'>
		 <i class="fa fa-user">&ensp;</i>
		<%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
	</li>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>



<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Finance Tracker", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
        <%= render 'layouts/navigation_links' %>
    </ul>
    <ul class="navbar-nav ml-auto">
        <%= render 'layouts/nav_links_for_auth' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to "Home", root_path, class: "nav-link" %>
<%= link_to "Portfolio", users_my_portfolio_path, class: "nav-link" %>
<%= link_to "Stock Search", stocks_search_path, class: "nav-link" %>
<%= link_to "My Friends", my_friends_path, class: "nav-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Finance Tracker" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Finance Tracker" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/stocks/_result.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

<% if @stock %>
	<div class="well results-block">
	  <strong>Symbol: </strong> <%= @stock.ticker %>
	  <strong>Name: </strong> <%= @stock.name %>
	  <strong>Price: </strong> <%= @stock.last_price %>
	</div>
  <%= link_to "Add to portfolio", stocks_add_path(stock: @stock.ticker), method: :post, class: "btn btn-lg btn-success" %>
 <% end %>

app/views/stocks/_result.js.erb
$('#results').html('<%= j (render 'stocks/result.html') %>')

app/views/stocks/search.html.erb
<h1>Stocks</h1>
<h3>Search for Stocks: </h3>
<div id="stock-lockup">
	<%= form_tag "/stocks/search", remote: true, method: :get, id: "stock-lookup-form" do %>
		<div class="form-group row no-padding text-center col-md-12">
			<div class="col-md-10">
				<%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control search-box input-lg" %>
			</div>
			<div class="col-md-2">
				<%= button_tag(type: :submit, class: "btn btn-lg btn-success") do%>
					<i class="fa fa-search"></i> Look up a stock
				<% end %>
			</div>
		</div>			
	<% end %>
</div>
<div id="results">
  <%= render "result" %>
</div>

app/views/users/_portfolio.html.erb
<table class="table table-bordered">                         
  <tr>                          
    <th scope="col">Ticker</th>
    <th scope="col">Name</th>
    <th scope="col">Price</th>
    <th scope="col"></th>
  </tr>
	<% portfolio.each do |stock| %>     
  <tr>
    <td><%= stock.ticker %></td>  	
    <td><%= stock.name %></td>  	
    <td><%= stock.last_price %></td>  
    <% if user == current_user %>	
      <td><%= link_to "Delete", stocks_remove_stock_from_portfolio_path(stock: stock.ticker, user: current_user.id), method: :post %></td>  	
    <% else %>
      <td><%= link_to "Add to my Portfolio", stocks_add_path(stock: stock.ticker), method: :post %></td> 
    <% end %>

  </tr>
<% end %>                        	
</table> 

app/views/users/_result.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>



<% if @friends && @friends.size > 0  %>
  <table class="table table-bordered">                         
    <tr>                          
      <th scope="col">Name</th>
      <th scope="col">email</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
    <% @friends.each do |friend| %>      
    <tr>
      <td><%= friend.full_name %></td>    
      <td><%= friend.email %></td>    
      <td><%= link_to "Show", users_show_friend_path(friend_id: friend.id) %></td>    
      <% if current_user.friend_with?(friend.id) %>    
        <td><strong>You are friends</strong></td>
      <% else %>
        <td><%= link_to "Add to My Friends", users_add_friend_path(friend_id: friend.id), method: :post %></td>    
      <% end %>          
    </tr>
  <% end %>                         
  </table> 
  
<% end %>

app/views/users/_result.js.erb
$('#results').html('<%= j (render 'users/result.html') %>')

app/views/users/my_friends.html.erb
<h1>My Friends</h1>


<% if @my_friends.size > 0  %>
	<table class="table table-bordered">                         
	  <tr>                          
	    <th scope="col">Name</th>
	    <th scope="col">email</th>
	    <th scope="col"></th>
	    <th scope="col"></th>
	  </tr>
		<% @my_friends.each do |friend| %>      
	  <tr>
	    <td><%= friend.full_name %></td>  	
	    <td><%= friend.email %></td>  	
	    <td><%= link_to "Show", users_show_friend_path(friend_id: friend.id) %></td>  	
	    <td><%= link_to "Delete", users_remove_friend_path(friend_id: friend.id), method: :post %></td>  	
	  </tr>
	<% end %>                        	
	</table> 
<% else %> 
	<h4>No friends yet!</h4>
<% end %>

<%= link_to "Search Friends", users_search_friend_path %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<%= render "users/portfolio", :portfolio => @user_stocks, :user => @user %>

app/views/users/search_friend.html.erb
<h1>Search friends: </h1>

<div id="friend-lookup">
	<%= form_tag "/users/search_friend", remote: true, method: :get, id: "friend-lookup-form" do %>
		<div class="form-group row no-padding text-center col-md-12">
			<div class="col-md-10">
				<%= text_field_tag :search_input, params[:search_input], placeholder: "Email or Name of Friend", autofocus: true, class: "form-control search-box input-lg" %>

			</div>
			<div class="col-md-2">
				<%= button_tag(type: :submit, class: "btn btn-lg btn-success") do%>
					<i class="fa fa-search"></i> Search
				<% end %>
			</div>
		</div>			
	<% end %>
</div>


<div id="results">
  <%= render "result" %>
</div>

app/views/users/show_friend.html.erb
<h1>Friend Details</h1>

<table class="table table-bordered">                         
	  <tr>                          
	    <th scope="col">Name</th>
	    <th scope="col">email</th>
	 	  </tr> 
	  <tr>
	    <td><%= @friend.full_name %></td>  	
	    <td><%= @friend.email %></td>  		
	  </tr>                   	
</table> 

	<%= render "users/portfolio", :portfolio => @friend.stocks, :user => @friend %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>